### ISSUE TITLE
Registrar bounce back

### ISSUE THREAD

**Issue by rau** [rau/eAbsentee#12]
Send email to Virginia Dept of Elections if email to registrar bounces back.

**Comment by rau** [comment]
@waldoj Do you have the email for the state department of elections where a bounce back email should be sent/where the application should be sent?

**Comment by waldoj** [comment]
As of four years ago, it was [this](https://github.com/TrustTheVote-Project/horatio-server/blob/041122593e4b1e5762a4b1acf283369ef088f671/api/includes/settings.inc.php#L67).
