### ISSUE TITLE
Prohibit duplicate submissions

### ISSUE THREAD

**Issue by rau** [rau/eAbsentee#28]
https://github.com/TrustTheVote-Project/horatio-client/issues/52

Check if this is possible through what we created - perhaps spam the button, see if anything happens?

**Comment by sumanthratna** [comment]
https://github.com/raunakdaga/eAbsentee/blob/5597fc22ab0289d36ab4fd2c742d889cab5906fb/templates/form.html#L1066

The `onclick` attribute should disable the button immediately after it's clicked once.

**Comment by rau** [comment]
@sumanthratna Can you update this so it only disables upon redirect or upon confirmation?
