### ISSUE TITLE
Does my vote really count?

### ISSUE THREAD

**Issue by rau** [rau/eAbsentee#47]
Another video titled, "Does my vote really count?" with the subtitle, "In the 2017 election, one citizen's vote flipped party control of the entire Virginia House of Delegates" Link it to this YouTube video:
https://www.youtube.com/watch?v=usJyXlkl3G4&list=PL6VcIi8pOD4AW0wqQha2IGDwNN8Uh1Xgr&index=3&t=0s

Figure out how to have button/banner pop up

**Comment by rau** [comment]
https://www.appcues.com/blog/best-open-source-modal-window-plugins

**Comment by rau** [comment]
https://robinparisi.github.io/tingle/

**Comment by sumanthratna** [comment]
Closed by https://github.com/rau/eAbsentee/commit/380c95cf23efe11836b51577ee54b40640b6bfd3
