### ISSUE TITLE
Identify hosting

### ISSUE THREAD

**Issue by rau** [rau/eAbsentee#8]
https://github.com/TrustTheVote-Project/horatio-server/issues/4

Noted here, Virginia SBE runs off of PHP. For the time being, we have created this application in Flask. This could possibly change down the future. 

For now, possible options include:

https://www.pythonanywhere.com/

https://medium.com/the-andela-way/deploying-a-python-flask-app-to-heroku-41250bda27d0

Google App Engine

**Comment by sumanthratna** [comment]
Other options: 
- [TJHSST Director](https://director.tjhsst.edu/) is an option if we are allowed to use it, see https://director.tjhsst.edu/docs/dynamic-sites-on-director/
- Azure is an option, see https://github.com/Cojacfar/FlaskWeb
- AWS is an option, see https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-flask.html

**Comment by sumanthratna** [comment]
PythonAnywhere is probably our best option considering #33 - we can use [scheduled tasks](https://help.pythonanywhere.com/pages/ScheduledTasks/).

**Comment by raunakdaga** [comment]
PythonAnywhere seems like the best option for now. Will use domain name eAbsentee.com.
